### ISSUE TITLE
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of 

### ISSUE THREAD

**Issue by maiminhdung** [SiliQon-Development/CosmicCosmetics#1]
Hello
I got this error on my server and plugin not working 
Here is logs: https://pastebin.com/r5j5NMSr
Version plugin: 1.1.2
Server Version: 1.18.2
Sorry for bad english

**Comment by SiliqonDev** [comment]
Thank you for the report!
I have fixed the issue in the new version 1.1.3 which has been rolled out to spigot just now
